import streamlit as st
st.title('Hello Dear User',"\U0001F642")
st.header('Welcome to MEDITECH')
name=st.text_input('Full name')
age=st.number_input('Age', min_value=1,step=1)
DOB=st.text_input("DOB(DD-MM-YYYY)")
blood=st.text_input('Blood Group')
gender=st.selectbox("Gender",("Male","Female"),)
Insurance=st.text_input('Insurance number')
cn=st.text_input('Your contact number')
Address=st.text_area('Address')
en1=st.text_input('Family contact number 1')
enn1=st.text_input('Name of The contact person')
enr1=st.text_input('Relation to the person')
en2=st.text_input('Family contact number 2')
enn2=st.text_input('Name of The 2-contact person')
enr2=st.text_input('Relation to the 2-person')
allergies=st.text_area('Any allergies')
medical=st.text_area("Past medical history")
medicine=st.text_area('Current medications')
famhis=st.text_area('Family medical history')
con=st.checkbox('Consent to release your medical information to relevant healthcare providers?',('Yes','No'),)
